import type { Locale } from "@/i18n/config";

export const copy = {
  en: {
    calculators: "Calculators", principles: "How results work", api: "API", footer: "Built for clear decisions, not mysterious totals.", footerDetail: "Estimates show their assumptions and workings.", theme: "Toggle theme", language: "Language", badge: "Sri Lankan calculation tools", hero: "Useful numbers. Visible workings.", intro: "Quick calculations that run privately in your browser and show how each answer was formed.", choose: "Choose a calculator", available: "Available now", releaseCount: "calculators in this release", standard: "The standard", trust: "A result should earn your trust.", all: "All calculators", categoryIntro: "Compare transparent tools with visible inputs, calculation breakdowns, and assumptions.", about: "About this calculator", aboutDetail: "Results include normalized inputs, a calculation breakdown, assumptions, and warnings used for the estimate.", needed: "Information you will need", required: "required", optional: "optional", version: "Calculation", values: "Your values", valuesHelp: "These values stay in your browser for this calculation.", result: "Result", resultHelp: "Totals, workings, and declared assumptions.", calculating: "Calculating...", calculate: "Calculate result", invalid: "The calculation input is invalid.", unavailable: "The calculator definition is unavailable.", failed: "The calculation could not be completed.", assumptions: "Assumptions", warnings: "Check before deciding", inputs: "Normalized inputs", empty: "Enter your values to see a transparent breakdown here.", calculatedWith: "Calculated with", notFound: "Calculator not found",
  },
  si: {
    calculators: "ගණක", principles: "ප්‍රතිඵල සකස් වන ආකාරය", api: "API", footer: "පැහැදිලි තීරණ සඳහා සාදන ලදී.", footerDetail: "ඇස්තමේන්තු ඒවායේ උපකල්පන සහ ගණනය පෙන්වයි.", theme: "තේමාව මාරු කරන්න", language: "භාෂාව", badge: "ශ්‍රී ලංකාව සඳහා ගණනය කිරීමේ මෙවලම්", hero: "ප්‍රයෝජනවත් සංඛ්‍යා. පැහැදිලි ගණනය.", intro: "ඔබේ බ්‍රවුසරයේ පෞද්ගලිකව ක්‍රියාත්මක වන සහ පිළිතුර සෑදූ ආකාරය පෙන්වන ඉක්මන් ගණනය කිරීම්.", choose: "ගණකයක් තෝරන්න", available: "දැන් ලබාගත හැක", releaseCount: "මෙම නිකුතුවේ ගණක", standard: "අපගේ ප්‍රමිතිය", trust: "ප්‍රතිඵලයක් ඔබේ විශ්වාසය දිනාගත යුතුය.", all: "සියලු ගණක", categoryIntro: "ඇතුළත් කළ අගයන්, ගණනය කිරීමේ පියවර සහ උපකල්පන පෙන්වන මෙවලම් සසඳන්න.", about: "මෙම ගණකය ගැන", aboutDetail: "ප්‍රතිඵලයේ සම්මත කළ ආදාන, ගණනය කිරීමේ පියවර, උපකල්පන සහ අනතුරු ඇඟවීම් ඇතුළත් වේ.", needed: "ඔබට අවශ්‍ය තොරතුරු", required: "අනිවාර්යයි", optional: "විකල්පයි", version: "ගණනය", values: "ඔබේ අගයන්", valuesHelp: "මෙම ගණනය සඳහා අගයන් ඔබේ බ්‍රවුසරයේම පවතී.", result: "ප්‍රතිඵලය", resultHelp: "එකතු, ගණනය කිරීමේ පියවර සහ ප්‍රකාශිත උපකල්පන.", calculating: "ගණනය කරමින්...", calculate: "ප්‍රතිඵලය ගණනය කරන්න", invalid: "ඇතුළත් කළ දත්ත වලංගු නොවේ.", unavailable: "ගණක නිර්වචනය ලබාගත නොහැක.", failed: "ගණනය සම්පූර්ණ කළ නොහැකි විය.", assumptions: "උපකල්පන", warnings: "තීරණයට පෙර පරීක්ෂා කරන්න", inputs: "සම්මත කළ ආදාන", empty: "පැහැදිලි ගණනය කිරීමේ පියවර බැලීමට ඔබේ අගයන් ඇතුළත් කරන්න.", calculatedWith: "ගණනය කළේ", notFound: "ගණකය හමු නොවීය",
  },
  ta: {
    calculators: "கணிப்பான்கள்", principles: "முடிவுகள் இயங்கும் விதம்", api: "API", footer: "தெளிவான முடிவுகளுக்காக உருவாக்கப்பட்டது.", footerDetail: "மதிப்பீடுகள் அவற்றின் கருதுகோள்களையும் கணக்கீடுகளையும் காட்டுகின்றன.", theme: "தோற்றத்தை மாற்று", language: "மொழி", badge: "இலங்கைக்கான கணக்கீட்டுக் கருவிகள்", hero: "பயனுள்ள எண்கள். தெளிவான கணக்கீடுகள்.", intro: "உங்கள் உலாவியில் தனிப்பட்ட முறையில் இயங்கி, ஒவ்வொரு விடையும் உருவான விதத்தைக் காட்டும் விரைவான கணக்கீடுகள்.", choose: "ஒரு கணிப்பானைத் தேர்ந்தெடுங்கள்", available: "இப்போது கிடைக்கின்றன", releaseCount: "இந்த வெளியீட்டில் கணிப்பான்கள்", standard: "எமது தரநிலை", trust: "ஒரு முடிவு உங்கள் நம்பிக்கையைப் பெற வேண்டும்.", all: "அனைத்துக் கணிப்பான்கள்", categoryIntro: "உள்ளீடுகள், கணக்கீட்டுப் படிகள் மற்றும் கருதுகோள்களைக் காட்டும் கருவிகளை ஒப்பிடுங்கள்.", about: "இந்தக் கணிப்பான் பற்றி", aboutDetail: "முடிவில் சீராக்கப்பட்ட உள்ளீடுகள், கணக்கீட்டுப் படிகள், கருதுகோள்கள் மற்றும் எச்சரிக்கைகள் அடங்கும்.", needed: "உங்களுக்குத் தேவையான தகவல்கள்", required: "கட்டாயம்", optional: "விருப்பம்", version: "கணக்கீடு", values: "உங்கள் மதிப்புகள்", valuesHelp: "இந்தக் கணக்கீட்டிற்கான மதிப்புகள் உங்கள் உலாவியிலேயே இருக்கும்.", result: "முடிவு", resultHelp: "மொத்தங்கள், கணக்கீட்டுப் படிகள் மற்றும் தெரிவிக்கப்பட்ட கருதுகோள்கள்.", calculating: "கணக்கிடுகிறது...", calculate: "முடிவைக் கணக்கிடு", invalid: "உள்ளிட்ட தரவு செல்லுபடியாகாது.", unavailable: "கணிப்பான் வரையறை கிடைக்கவில்லை.", failed: "கணக்கீட்டை நிறைவு செய்ய முடியவில்லை.", assumptions: "கருதுகோள்கள்", warnings: "முடிவெடுக்கும் முன் சரிபாருங்கள்", inputs: "சீராக்கப்பட்ட உள்ளீடுகள்", empty: "தெளிவான கணக்கீட்டுப் படிகளைக் காண உங்கள் மதிப்புகளை உள்ளிடுங்கள்.", calculatedWith: "கணக்கிட்டது", notFound: "கணிப்பான் கிடைக்கவில்லை",
  },
} as const satisfies Record<Locale, Record<string, string>>;

export type UiCopy = (typeof copy)[Locale];
